url: https://wanderahead.com
title: Wander Ahead
author: Cheryl Rodewig

permalink: /:title/
collections:
  posts:
    output: true
    permalink: /article/:title/
  destinations:
    output: false
    permalink: /:name/

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false

sass:
  sass_dir: css
  style: compressed

# Category pagination settings
category_pagination:
  enabled: true
  per_page: 1

defaults:
  - scope:
      path: "assets/*"
    values:
      sitemap: false
  - scope:
      path: ""
    values:
      layout: default
      title: Wander Ahead
      image: /assets/img/default/wander-ahead.webp
